In [1]:
import pandas as pd

In [2]:
# Read the CSV file subway_stations.csv into a DataFrame called df

df = pd.read_csv('../../05_src/data/slides_data/subway_stations.csv')

print(df)

     stop_lat   stop_lon             station
0   43.666061 -79.411065    BATHURST STATION
1   43.670149 -79.390089         BAY STATION
2   43.766872 -79.386703     BAYVIEW STATION
3   43.769202 -79.376312   BESSARION STATION
4   43.670049 -79.385389       BLOOR STATION
..        ...        ...                 ...
72  43.734475 -79.450920      WILSON STATION
73  43.686440 -79.312471    WOODBINE STATION
74  43.670997 -79.385956       YONGE STATION
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

[77 rows x 3 columns]

In [3]:
# Display the first 5 rows of the DataFrame

df.head()

    stop_lat   stop_lon            station
0  43.666061 -79.411065   BATHURST STATION
1  43.670149 -79.390089        BAY STATION
2  43.766872 -79.386703    BAYVIEW STATION
3  43.769202 -79.376312  BESSARION STATION
4  43.670049 -79.385389      BLOOR STATION

In [4]:
# Display the last 2 rows of the DataFrame

df.tail(2)

     stop_lat   stop_lon             station
75  43.745172 -79.405930  YORK MILLS STATION
76  43.725248 -79.447692    YORKDALE STATION

In [8]:
# Check the number of rows and columns in the DataFrame

df.shape

(77, 3)

In [10]:
# Check the data types in the DataFrame

df.dtypes

stop_lat    float64
stop_lon    float64
station         str
dtype: object

In [34]:
# Filter the DataFrame to show only rows where station is "COLLEGE STATION " or "ROYAL YORK STATION"

stations_of_interest = ['COLLEGE STATION', 'ROYAL YORK STATION']

# filter using .loc[] and .isin()
filtered_stations = df.loc[df["station"].isin(stations_of_interest)]

print(filtered_stations)

     stop_lat   stop_lon             station
9   43.660149 -79.382688     COLLEGE STATION
54  43.648338 -79.511178  ROYAL YORK STATION

In [ ]:
# access rows of data where line is NA 
# df.loc[df["Bike_Model"].isna()]

# access rows of data where line is NA 
# df.query("Bike_Model.isna()")

UNION_STATION_LON = -79.37921
UNION_STATION_LAT = 43.645652

def search_by_station():
    user_station_query = input("What station would you like info for? > ")
    if "STATION" in user_station_query.upper():
        user_station_query = user_station_query[:-8]

    filtered = df.loc[df["station"]==((user_station_query.upper()) + " STATION")]
    return filtered

search_by_station()

    stop_lat   stop_lon          station
9  43.660149 -79.382688  COLLEGE STATION

In [40]:
# Export the filtered DataFrame to a CSV file called exported_data.csv

filtered_stations.to_csv("exported_data.csv")

with open("exported_data.csv", "r") as f:
    print(f.readlines())

[',stop_lat,stop_lon,station\n', '9,43.660149,-79.382688,COLLEGE STATION\n', '54,43.648338,-79.511178,ROYAL YORK STATION\n']